SESWrapper: WEvent Class Reference
WEvent Class Reference
This class is used as a container for one event.
#include <wevent.h>
Public Types
enum ErrorCodes { ERR_OK = 0, ERR_TIMEOUT = -1 }
Public Member Functions
WEvent ()
~WEvent ()
void set ()
void reset ()
int wait (int timeout=-1) const
HANDLE handle () const
Detailed Description
This class is used as a container for one event.
The following example shows one way of using WEvent:
using SciCoreNS::WThread;
using SciCoreNS::WEvent;
class MyThread : public WThread
{
public:
  void stop()
  {
    abort_.set();
  }
  void trigger()
  {
    ready_.set();
  }
protected:
  void run()
  {
    abort_.reset();
    ready_.reset();
    bool running_ = true;
    std::vector<WEvent *> events;
    events.push_back(&abort_);
    while(running_)
    {
      int result = ready_.wait(-1, events);
      switch (result)
      {
      case 0:
        std::cout << "Data arrived!" << std::endl;
        ready_.reset();
        break;
      case 1:
        std::cout << "Exiting..." << std::endl;
        running_ = false;
        break;
      }
    }
  }
private:
  WEvent ready_;
  WEvent abort_;
};
int main(int argc, char **argv)
{
  using std::cout;
  using std::cin;
  using std::endl;
  MyThread thread;
  thread.start();
  while (1)
  {
    cout << "Command (1: Data arrived, 2: Exit): ";
    char c = cin.get();
    cin.get();
    if (c == '1')
    {
      thread.trigger();
    }
    else if (c == '2')
    {
      thread.stop();
      thread.wait();
      cout << "Done" << endl;
      break;
    }
  }
  return 0;
}
Definition at line 8 of file wevent.h.
Constructor & Destructor Documentation
WEvent::WEvent () [inline]
Constructs a WEvent object that contains an event handle.
Definition at line 32 of file wevent.h.
WEvent::~WEvent () [inline]
Destroys an event object and closes the contained event handle.
Definition at line 40 of file wevent.h.
Member Function Documentation
HANDLE WEvent::handle () const [inline]
Convenience member function for obtaining the handle to the contained event object.
Returns:
Returns the event handle for use in calls to e.g. WaitForMultipleObjects().
Definition at line 79 of file wevent.h.
Referenced by WSESWrapperMain::waitForPointReady(), and WSESWrapperMain::waitForRegionReady().
void WEvent::reset () [inline]
Places the contained event object in an unsignalled state.
Definition at line 56 of file wevent.h.
Referenced by WSESWrapperMain::continueAcquisition(), WSESWrapperMain::initAcquisition(), WSESWrapperMain::startAcquisition(), and WSESWrapperMain::stopAcquisition().
void WEvent::set () [inline]
Signals the contained event object.
Definition at line 48 of file wevent.h.
Referenced by WSESWrapperMain::continueAcquisition(), WSESWrapperMain::finalize(), and WSESWrapperMain::stopAcquisition().
int WEvent::wait (int timeout = -1) const [inline]
Waits for the contained event object to be in a signalled state.
Parameters:
[in] timeout The number of milliseconds to wait before time-out. The default is to never time out.
Returns:
ERR_OK if the current event is signalled. otherwise ERR_TIMEOUT.
Definition at line 69 of file wevent.h.
The documentation for this class was generated from the following file:
C:/Development/svn/seswrapper-lib/include/wevent.h