SESWrapper: WSESWrapperBase Class Reference
WSESWrapperBase Class Reference
Public Types
typedef WVariable
< WSESWrapperBase > Property
typedef std::pair< std::string,
Property > PropertyKeyValue
typedef std::map< std::string,
Property > PropertyMap
typedef std::vector< std::string > NameVector
typedef std::vector< double > DoubleVector
typedef int(* guiCallback)()
typedef std::map< std::string,
guiCallback > SesGuiMap
Public Member Functions
WSESWrapperBase ()
~WSESWrapperBase ()
Protected Member Functions
int getLibDescription (int index, void *value, int &size)
int getLibVersion (int index, void *value, int &size)
int getLibError (int index, void *value, int &size)
int getLibWorkingDir (int index, void *value, int &size)
int getInstrumentLibrary (int index, void *value, int &size)
int getInstrumentStatus (int index, void *value, int &size)
int getAlwaysDelayRegion (int index, void *value, int &size)
int getAllowIOWithDetector (int index, void *value, int &size)
int getInstrumentModel (int index, void *value, int &size)
int getInstrumentSerialNo (int index, void *value, int &size)
int getDetectorInfo (int index, void *value, int &size)
int getDetectorRegion (int index, void *value, int &size)
int getElementSetCount (int index, void *value, int &size)
int getElementSet (int index, void *value, int &size)
int getElementNameCount (int index, void *value, int &size)
int getElementName (int index, void *value, int &size)
int getLensModeCount (int index, void *value, int &size)
int getLensMode (int index, void *value, int &size)
int getPassEnergyCount (int index, void *value, int &size)
int getPassEnergy (int index, void *value, int &size)
int getAnalyzerRegion (int index, void *value, int &size)
int getUseExternalIO (int index, void *value, int &size)
int getUseDetector (int index, void *value, int &size)
int getRegionName (int index, void *value, int &size)
int getTempFileName (int index, void *value, int &size)
int getResetDataBetweenIterations (int index, void *value, int &size)
int getUseSpin (int index, void *value, int &size)
int getUseBindingEnergy (int index, void *value, int &size)
int readOnlyStub (int index, const void *value)
int setLibWorkingDir (int index, const void *value)
int setInstrumentLibrary (int index, const void *value)
int setAlwaysDelayRegion (int index, const void *value)
int setAllowIOWithDetector (int index, const void *value)
int setDetectorRegion (int index, const void *value)
int setElementSet (int index, const void *value)
int setLensMode (int index, const void *value)
int setPassEnergy (int index, const void *value)
int setAnalyzerRegion (int index, const void *value)
int setUseExternalIO (int index, const void *value)
int setUseDetector (int index, const void *value)
int setRegionName (int index, const void *value)
int setTempFileName (int index, const void *value)
int setResetDataBetweenIterations (int index, const void *value)
int setUseSpin (int index, const void *value)
int setUseBindingEnergy (int index, const void *value)
bool loadElementSets ()
bool loadLensModes ()
bool loadPassEnergies (const std::string &lensMode, DoubleVector &result)
bool loadElementNames ()
void splitSESList (const char *buffer, int bufferSize, NameVector &result)
Protected Attributes
PropertyMap properties_
WSESInstrument * lib_
bool instrumentLoaded_
std::string workingDir_
std::string instrumentLibraryName_
SesNS::WInstrumentInfo sesInstrumentInfo_
SesNS::WDetectorInfo sesDetectorInfo_
SesNS::WDetector sesDetectorRegion_
SesNS::WRegion sesRegion_
std::string tempFileName_
unsigned short activeDetectors_
NameVector elementSets_
NameVector lensModes_
DoubleVector passEnergies_
NameVector elementNames_
unsigned int startTime_
SesGuiMap sesGUI_
bool blockPointReady_
bool blockRegionReady_
bool resetDataBetweenIterations_
int iteration_
WError * errors_
Detailed Description
This class collects all variables and objects for SESWrapper.
It serves as a container for property callbacks used when "setting" or "getting" values for the Properties properties.
Definition at line 14 of file wseswrapperbase.h.
Constructor & Destructor Documentation
WSESWrapperBase::WSESWrapperBase ()
Creates a WSESWrapperBase instance. Also creates the hash table for the Properties, where the property names are linked to their corresponding callbacks through instances of the WVariable template class.
Parameters:
[in] workingDir The current working directory.
Definition at line 35 of file wseswrapperbase.cpp.
References getAllowIOWithDetector(), getAlwaysDelayRegion(), getAnalyzerRegion(), getDetectorInfo(), getDetectorRegion(), getElementName(), getElementNameCount(), getElementSet(), getElementSetCount(), getInstrumentLibrary(), getInstrumentModel(), getInstrumentSerialNo(), getInstrumentStatus(), getLensMode(), getLensModeCount(), getLibDescription(), getLibError(), getLibVersion(), getLibWorkingDir(), getPassEnergy(), getPassEnergyCount(), getRegionName(), getResetDataBetweenIterations(), getTempFileName(), getUseBindingEnergy(), getUseDetector(), getUseExternalIO(), getUseSpin(), WError::instance(), readOnlyStub(), setAllowIOWithDetector(), setAlwaysDelayRegion(), setAnalyzerRegion(), setDetectorRegion(), setElementSet(), setInstrumentLibrary(), setLensMode(), setLibWorkingDir(), setPassEnergy(), setRegionName(), setResetDataBetweenIterations(), setTempFileName(), setUseBindingEnergy(), setUseDetector(), setUseExternalIO(), setUseSpin(), WVariable< _Container >::TYPE_ANALYZERREGION, WVariable< _Container >::TYPE_BOOL, WVariable< _Container >::TYPE_DETECTORINFO, WVariable< _Container >::TYPE_DETECTORREGION, WVariable< _Container >::TYPE_DOUBLE, WVariable< _Container >::TYPE_INT32, and WVariable< _Container >::TYPE_STRING.
WSESWrapperBase::~WSESWrapperBase ()
Destroys the WSESWrapperBase object.
Definition at line 82 of file wseswrapperbase.cpp.
References WError::release().
Member Function Documentation
int WSESWrapperBase::getAllowIOWithDetector (int index, void * value, int & size) [protected]
Getter for the allow_io_with_detector property. The value parameter must be a pointer to a 1-byte boolean. If value is 1 or true, external I/O signalling and detector can be used simultaneously.
Parameters:
[in] index Not used.
[out] value Pointer to a 1-byte boolean.
[in,out] size Not used.
Returns:
If WSESWrapperMain::loadInstrument() has not been called, returns WError::ERR_NO_INSTRUMENT, otherwise WError::ERR_OK.
Definition at line 247 of file wseswrapperbase.cpp.
References WError::ERR_NO_INSTRUMENT, WError::ERR_OK, and WSESInstrument::GDS_GetOption.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getAlwaysDelayRegion (int index, void * value, int & size) [protected]
Getter for the always_delay_region property. The value parameter must be a pointer to a 1-byte boolean. If value is 1 or true, there is a delay before starting a measurement.
Parameters:
[in] index Not used.
[out] value Pointer to a 1-byte boolean.
[in,out] size Not used.
Returns:
If WSESWrapperMain::loadInstrument() has not been called, returns WError::ERR_NO_INSTRUMENT, otherwise WError::ERR_OK.
Definition at line 227 of file wseswrapperbase.cpp.
References WError::ERR_NO_INSTRUMENT, WError::ERR_OK, and WSESInstrument::GDS_GetOption.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getAnalyzerRegion (int index, void * value, int & size) [protected]
Getter for the analyzer_region property.
Parameters:
[in] index Not used.
[out] value A pointer to a SESWrapperNS::AnalyzerRegion structure.
[in,out] size Not used.
Returns:
WError::ERR_NO_INSTRUMENT if WSESWrapperMain::loadInstrument() has not been called, otherwise WError::ERR_OK.
Definition at line 620 of file wseswrapperbase.cpp.
References SESWrapperNS::WAnalyzerRegion::centerEnergy_, SESWrapperNS::WAnalyzerRegion::dwellTime_, SESWrapperNS::WAnalyzerRegion::energyStep_, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, SESWrapperNS::WAnalyzerRegion::fixed_, SESWrapperNS::WAnalyzerRegion::highEnergy_, and SESWrapperNS::WAnalyzerRegion::lowEnergy_.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getDetectorInfo (int index, void * value, int & size) [protected]
Getter for the detector_info property.
Parameters:
[in] index Not used.
[out] value A pointer to a SESWrapperNS::DetectorInfo structure.
[in,out] size Not used.
Returns:
WError::ERR_NO_INSTRUMENT if WSESWrapperMain::loadInstrument() has not been called, otherwise WError::ERR_OK.
Definition at line 309 of file wseswrapperbase.cpp.
References SESWrapperNS::WDetectorInfo::adcPresent_, SESWrapperNS::WDetectorInfo::discPresent_, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, SESWrapperNS::WDetectorInfo::frameRate_, WSESInstrument::GDS_GetDetectorInfo, SESWrapperNS::WDetectorInfo::maxChannels_, SESWrapperNS::WDetectorInfo::maxSlices_, SESWrapperNS::WDetectorInfo::timerControlled_, SESWrapperNS::WDetectorInfo::xChannels_, and SESWrapperNS::WDetectorInfo::yChannels_.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getDetectorRegion (int index, void * value, int & size) [protected]
Getter for the detector_region property.
Parameters:
[in] index Not used.
[out] value A pointer to a SESWrapperNS::DetectorRegion structure.
[in,out] size Not used.
Returns:
WError::ERR_NO_INSTRUMENT if WSESWrapperMain::loadInstrument() has not been called, otherwise WError::ERR_OK.
Definition at line 343 of file wseswrapperbase.cpp.
References SESWrapperNS::WDetectorRegion::adcMode_, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, SESWrapperNS::WDetectorRegion::firstXChannel_, SESWrapperNS::WDetectorRegion::firstYChannel_, SESWrapperNS::WDetectorRegion::lastXChannel_, SESWrapperNS::WDetectorRegion::lastYChannel_, and SESWrapperNS::WDetectorRegion::slices_.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getElementName (int index, void * value, int & size) [protected]
Getter for the element_name property. If the value parameter is 0, size will be modified to return the required buffer length for the requested element name.
Parameters:
[in] index If 0 <= index < element_name_count, obtains the element name for that index.
[out] value A char* buffer to be filled with an element name. Can be 0 (NULL).
[in,out] size If value is non-null, this parameter is assumed to contain the maximum size of the buffer.
Returns:
WError::ERR_NO_INSTRUMENT if WSESWrapperMain::loadInstrument() has not been called, WError::ERR_FAIL on failure to report the element name, WError::ERR_INDEX if index is out-of-range, otherwise WError::ERR_OK.
Definition at line 464 of file wseswrapperbase.cpp.
References WError::ERR_INDEX, WError::ERR_NO_INSTRUMENT, and WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getElementNameCount (int index, void * value, int & size) [protected]
Getter for the element_name_count property. The value parameter must be a pointer to a 32-bit integer.
Parameters:
[in] index Not used.
[out] value A 32-bit integer that will contain the number of available element names. This value can later be used as an index to the element_name property getter.
[in,out] size Not used.
Returns:
WError::ERR_NO_INSTRUMENT if WSESWrapperMain::loadInstrument() has not been called, otherwise WError::ERR_OK.
See also:
WSESWrapperBase::getElementName()
Definition at line 439 of file wseswrapperbase.cpp.
References WError::ERR_NO_INSTRUMENT, and WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getElementSet (int index, void * value, int & size) [protected]
Getter for the element_set property. If the value parameter is 0, size will be modified to return the required buffer length for the requested element set.
Parameters:
[in] index If set to -1, obtains the current element set. If 0 <= index < element_set_count, obtains the element set name for that index.
[out] value A char* buffer to be filled with an element set. Can be 0 (NULL).
[in,out] size If value is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting buffer.
Returns:
WError::ERR_NO_INSTRUMENT if WSESWrapperMain::loadInstrument() has not been called, WError::ERR_FAIL on failure to report the current element set, WError::ERR_INDEX if index is out-of-range, otherwise WError::ERR_OK.
Definition at line 401 of file wseswrapperbase.cpp.
References WError::ERR_FAIL, WError::ERR_INDEX, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, and WSESInstrument::GDS_GetCurrElementSet.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getElementSetCount (int index, void * value, int & size) [protected]
Getter for the element_set_count property. The value parameter must be a pointer to a 32-bit integer.
Parameters:
[in] index Not used.
[out] value A 32-bit integer that will contain the number of available element sets. This value can later be used as an index to the element_set_from_index property getter.
[in,out] size Not used.
Returns:
WError::ERR_NO_INSTRUMENT if WSESWrapperMain::loadInstrument() has not been called, otherwise WError::ERR_OK.
See also:
WSESWrapperBase::getElementSetFromIndex()
Definition at line 376 of file wseswrapperbase.cpp.
References WError::ERR_NO_INSTRUMENT, and WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getInstrumentLibrary (int index, void * value, int & size) [protected]
Getter for the instrument_library property. If the value parameter is 0, size will be modified to return the required buffer length for the description.
Parameters:
[in] index Not used.
[out] value A char* buffer to be filled with the instrument library file name. Can be 0 (NULL).
[in,out] size If value is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array.
Returns:
Always returns WError::ERR_OK.
Definition at line 99 of file wseswrapperbase.cpp.
References WError::ERR_OK, and SESWrapperNS::gLibraryName.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getInstrumentModel (int index, void * value, int & size) [protected]
Getter for the instrument_model property. If the value parameter is 0, size will be modified to return the required buffer length. If WSESWrapperMain::loadInstrument() has not been called, value is usually empty, but do not rely on it.
Parameters:
[in] index Not used.
[out] value A char* buffer to be filled with the name of the instrument model. Can be 0 (NULL).
[in,out] size If value is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array.
Returns:
Always returns WError::ERR_OK.
Definition at line 269 of file wseswrapperbase.cpp.
References WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getInstrumentSerialNo (int index, void * value, int & size) [protected]
Getter for the instrument_serial_no property. If the value parameter is 0, size will be modified to return the required buffer length. If WSESWrapperMain::loadInstrument() has not been called, value is usually empty, but do not rely on it.
Parameters:
[in] index Not used.
[out] value A char* buffer to be filled with the name of the instrument serial number. Can be 0 (NULL).
[in,out] size If value is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array.
Returns:
Always returns WError::ERR_OK.
Definition at line 290 of file wseswrapperbase.cpp.
References WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getInstrumentStatus (int index, void * value, int & size) [protected]
Getter for the instrument_status property. The value parameter must be a pointer to an 32-bit integer.
Parameters:
[in] index Not used.
[out] value Pointer to a 32-bit integer. Possible values are given by SesNS::InstrumentStatus.
[in,out] size Not used.
Returns:
Always returns WError::ERR_OK.
Definition at line 206 of file wseswrapperbase.cpp.
References WError::ERR_OK, WSESInstrument::GDS_GetStatus, WLibrary::isLoaded(), and SesNS::NonOperational.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getLensMode (int index, void * value, int & size) [protected]
Getter for the lens_mode property. If the value parameter is 0, size will be modified to return the required buffer length for the requested lens mode.
Parameters:
[in] index If set to -1, obtains the current lens mode. If 0 <= index < lens_mode_count, obtains the lens mode name for that index.
[out] value A char* buffer to be filled with the current lens mode. Can be 0 (NULL).
[in,out] size If value is 0, this parameter is modified with the required size of the buffer, otherwise it is used to determine the size of value.
Returns:
WError::ERR_NO_INSTRUMENT if WSESWrapperMain::loadInstrument() has not been called, WError::ERR_FAIL on failure to report the current lens mode, WError::ERR_INDEX if index is out-of-range, otherwise WError::ERR_OK.
Definition at line 521 of file wseswrapperbase.cpp.
References WError::ERR_FAIL, WError::ERR_INDEX, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, and WSESInstrument::GDS_GetCurrLensMode.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getLensModeCount (int index, void * value, int & size) [protected]
Getter for the lens_mode_count property. The value parameter must be a pointer to a 32-bit integer.
Parameters:
[in] index Not used.
[out] value A 32-bit integer that will contain the number of available lens modes. This value can later be used as an index to the lens_mode_from_index property getter.
[in,out] size Not used.
Returns:
WError::ERR_NO_INSTRUMENT if WSESWrapperMain::loadInstrument() has not been called, otherwise WError::ERR_OK.
See also:
WSESWrapperBase::getLensModeFromIndex(), WSESWrapperBase::getLensMode()
Definition at line 496 of file wseswrapperbase.cpp.
References WError::ERR_NO_INSTRUMENT, and WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getLibDescription (int index, void * value, int & size) [protected]
Getter for the lib_description property. If the value parameter is 0, size will be modified to return the required buffer length for the description.
Parameters:
[in] index Not used.
[out] value A char* buffer to be filled with the description. Can be 0 (NULL).
[in,out] size If value is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array.
Returns:
Always returns WError::ERR_OK.
Definition at line 119 of file wseswrapperbase.cpp.
References WError::ERR_OK, and SESWrapperNS::gLibraryName.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getLibError (int index, void * value, int & size) [protected]
Getter for the lib_error variable. If the value parameter is 0, size will be modified to return the required buffer length for the error indicated by index.
Parameters:
[in] index An error code, e.g. from a previously returned function. If index is not a valid error code, the error string is "Unknown Error".
[out] value A char* buffer to be filled with the error message connected to error code index. Can be 0 (NULL).
[in,out] size If value is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array.
Returns:
Always returns WError::ERR_OK;
Definition at line 161 of file wseswrapperbase.cpp.
References WError::ERR_OK, and WError::message().
Referenced by WSESWrapperBase().
int WSESWrapperBase::getLibVersion (int index, void * value, int & size) [protected]
Getter for the lib_version property. If the value parameter is 0, size will be modified to return the required buffer length for the version.
Parameters:
[in] index Not used.
[out] value A char* buffer to be filled with the version. The syntax is
 <major>.<minor>.<build>
. Can be 0 (NULL).
[in,out] size If value is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array.
Returns:
Always returns WError::ERR_OK.
Definition at line 140 of file wseswrapperbase.cpp.
References WError::ERR_OK, and SESWrapperNS::gVersion.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getLibWorkingDir (int index, void * value, int & size) [protected]
Getter for the lib_working_dir property. If the value parameter is 0, size will be modified to return the required buffer length.
Parameters:
[in] index Not used.
[out] value A char* buffer to be filled with the full path of the current working directory. Can be 0 (NULL).
[in,out] size If value is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array.
Returns:
Always returns WError::ERR_OK.
Definition at line 183 of file wseswrapperbase.cpp.
References WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getPassEnergy (int index, void * value, int & size) [protected]
Getter for the pass_energy property. The value parameter must be a pointer to a double (8-byte floating point).
Parameters:
[in] index If set to -1, obtains the current pass energy. If 0 <= index < pass_energy_count, obtains the pass energy for that index.
[out] value A pointer to a double to be filled with the current pass energy.
[in,out] size Not used.
Returns:
WError::ERR_NO_INSTRUMENT if WSESWrapperMain::loadInstrument() has not been called, WError::ERR_FAIL on failure to report the current pass energy, WError::ERR_INDEX if index is out-of-range, otherwise WError::ERR_OK.
Definition at line 586 of file wseswrapperbase.cpp.
References WError::ERR_FAIL, WError::ERR_INDEX, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, and WSESInstrument::GDS_GetCurrPassEnergy.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getPassEnergyCount (int index, void * value, int & size) [protected]
Getter for the pass_energy_count property. The value parameter must be a pointer to a 32-bit integer.
Note:
The number of available pass energies is dependent on the current lens mode. If you change the lens mode, you need to update your internal list of pass energies, beginning with this function.
Parameters:
[in] index Not used.
[out] value A 32-bit integer that will contain the number of available lens modes. This value can later be used as an index to the lens_mode_from_index property getter.
[in,out] size Not used.
Returns:
WError::ERR_NO_INSTRUMENT if WSESWrapperMain::loadInstrument() has not been called, otherwise WError::ERR_OK.
See also:
WSESWrapperBase::getLensModeFromIndex(), WSESWrapperBase::getLensMode()
Definition at line 561 of file wseswrapperbase.cpp.
References WError::ERR_NO_INSTRUMENT, and WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getRegionName (int index, void * value, int & size) [protected]
Getter for the region_name property.
Parameters:
[in] index Not used.
[out] value A char* buffer to be filled with the name of the region. Can be 0 (NULL).
[in,out] size If value is 0, this parameter is modified with the required length of the region name, otherwise it is used to determine the size of value.
Returns:
Always returns WError::ERR_OK.
Definition at line 693 of file wseswrapperbase.cpp.
References WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getResetDataBetweenIterations (int index, void * value, int & size) [protected]
Getter for the reset_data_between_iterations property.
Parameters:
[in] index Not used.
[out] value A pointer to a 1-byte boolean. If value is 0 (or false), data will be accumulated between each call to startAcquisition unless initAcquisition is called. If it is 1 (or true), all data is reset to 0 between the iterations, even if initAcquisition is not called.
[in,out] size Not used.
Returns:
Always returns WError::ERR_OK.
Definition at line 733 of file wseswrapperbase.cpp.
References WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getTempFileName (int index, void * value, int & size) [protected]
Getter for the temp_file_name property.
Parameters:
[in] index Not used.
[out] value A char* buffer to be filled with the name of the temporary working file created during acquisition. Can be 0 (NULL).
[in,out] size If value is 0, this parameter is modified with the required length of the file name, otherwise it is used to determine the size of value.
Returns:
Always returns WError::ERR_OK.
Definition at line 713 of file wseswrapperbase.cpp.
References WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getUseBindingEnergy (int index, void * value, int & size) [protected]
Getter for the use_binding_energy property.
Parameters:
[in] index Not used.
[out] value A pointer to a 1-byte boolean. Set to true when the energies in the analyzer region are assumed to be given as binding energies.
[in,out] size Not used.
Returns:
Always returns WError::ERR_OK.
Definition at line 787 of file wseswrapperbase.cpp.
References WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getUseDetector (int index, void * value, int & size) [protected]
Getter for the use_detector property.
Parameters:
[in] index Not used.
[out] value A pointer to a 1-byte boolean. If value is 0 (or false), no communication with the detector is made.
[in,out] size Not used.
Returns:
WError::ERR_NO_INSTRUMENT if WSESWrapperMain::loadInstrument() has not been called, otherwise WError::ERR_OK.
Definition at line 672 of file wseswrapperbase.cpp.
References WError::ERR_NO_INSTRUMENT, and WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getUseExternalIO (int index, void * value, int & size) [protected]
Getter for the use_external_io property.
Parameters:
[in] index Not used.
[out] value A pointer to a 1-byte boolean. If value is 0 (or false), no communication with the external I/O card is made. One example of an external I/O card is the DAQ cards from National Instruments.
[in,out] size Not used.
Returns:
WError::ERR_NO_INSTRUMENT if WSESWrapperMain::loadInstrument() has not been called, otherwise WError::ERR_OK.
Definition at line 650 of file wseswrapperbase.cpp.
References WError::ERR_NO_INSTRUMENT, and WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::getUseSpin (int index, void * value, int & size) [protected]
Getter for the use_spin property. If there are no spin detectors installed, this function returns WError::ERR_NOT_APPLICABLE and sets value to false.
Parameters:
[in] index Specifies which spin detector being queried. The value ranges between 1 and the number of available spin detectors. Which spin detector belongs to what index depends on the system configuration.
[out] value A pointer to a 1-byte boolean. This is set to true if the spin detector specified by index is active.
[in,out] size Not used.
Returns:
WError::ERR_OK if a spin detector is found at index index.
Definition at line 753 of file wseswrapperbase.cpp.
References WError::ERR_INDEX, WError::ERR_NO_INSTRUMENT, WError::ERR_NOT_APPLICABLE, WError::ERR_OK, and WSESInstrument::GDS_GetOption.
Referenced by WSESWrapperBase().
bool WSESWrapperBase::loadElementNames () [protected]
Reloads the Element names. Called after loading a new instrument configuration.
Returns:
true if successful.
Definition at line 1253 of file wseswrapperbase.cpp.
References WSESInstrument::GDS_GetElements, and splitSESList().
Referenced by WSESWrapperMain::loadInstrument().
bool WSESWrapperBase::loadElementSets () [protected]
Reloads the elemet sets. Called after loading a new instrument configuration.
Returns:
true if successful.
Definition at line 1164 of file wseswrapperbase.cpp.
References WSESInstrument::GDS_GetElementSets, and splitSESList().
Referenced by WSESWrapperMain::loadInstrument().
bool WSESWrapperBase::loadLensModes () [protected]
Loads the lens modes. Called after loading a new instrument configuration.
Returns:
true if successful.
Definition at line 1191 of file wseswrapperbase.cpp.
References WSESInstrument::GDS_GetLensModes, and splitSESList().
Referenced by WSESWrapperMain::loadInstrument().
bool WSESWrapperBase::loadPassEnergies (const std::string & lensMode, DoubleVector & result) [protected]
Reloads the Pass energies. Called after loading a new instrument configuration.
Returns:
true if successful.
Definition at line 1218 of file wseswrapperbase.cpp.
References WSESInstrument::GDS_GetPassEnergies, and splitSESList().
Referenced by WSESWrapperMain::loadInstrument(), and WSESWrapperMain::validate().
int WSESWrapperBase::readOnlyStub (int index, const void * value) [protected]
Stub for the read-only properties.
Parameters:
[in] index Not used.
[in] value Not used.
Returns:
Always returns WError::ERR_READONLY to indicate that an attempt was made to modify a read-only property.
Definition at line 805 of file wseswrapperbase.cpp.
References WError::ERR_READONLY.
Referenced by WSESWrapperBase().
int WSESWrapperBase::setAllowIOWithDetector (int index, const void * value) [protected]
Setter for the allow_io_with_detector property. If true (1), external I/O communication will be possible simultaneously with detector communication.
Parameters:
[in] index Not used.
[in] value A 1-byte boolean of value true (1) or false (0).
Returns:
WError::ERR_NOT_INITIALIZED if the library has not been successfully initialized, otherwise WError::ERR_OK.
Definition at line 889 of file wseswrapperbase.cpp.
References WError::ERR_NOT_INITIALIZED, WError::ERR_OK, and WSESInstrument::GDS_SetOption.
Referenced by WSESWrapperBase().
int WSESWrapperBase::setAlwaysDelayRegion (int index, const void * value) [protected]
Setter for the always_delay_region property. If true (1), a delay will be made before starting the acquisition of a region.
Parameters:
[in] index Not used.
[in] value A 1-byte boolean of value true (1) or false (0).
Returns:
WError::ERR_NOT_INITIALIZED if the library has not been successfully initialized, otherwise WError::ERR_OK.
Definition at line 871 of file wseswrapperbase.cpp.
References WError::ERR_NOT_INITIALIZED, WError::ERR_OK, and WSESInstrument::GDS_SetOption.
Referenced by WSESWrapperBase().
int WSESWrapperBase::setAnalyzerRegion (int index, const void * value) [protected]
Setter for the analyzer_region property. The members in the WAnalyzerRegion structure are stored in an internal object for later use in a call to WSESWrapperMain::initAcquisition(). There is no immediate checking done of the validity of the given values. If such a check is required before starting acquisition, the WSESWrapperMain::checkAnalyzerRegion() can be called.
Parameters:
[in] index Not used.
[in] value A pointer to a WAnalyzerRegion structure.
Returns:
Always returns WError::ERR_OK.
Definition at line 1010 of file wseswrapperbase.cpp.
References SESWrapperNS::WAnalyzerRegion::centerEnergy_, SESWrapperNS::WAnalyzerRegion::dwellTime_, SESWrapperNS::WAnalyzerRegion::energyStep_, WError::ERR_OK, SESWrapperNS::WAnalyzerRegion::fixed_, SESWrapperNS::WAnalyzerRegion::highEnergy_, and SESWrapperNS::WAnalyzerRegion::lowEnergy_.
Referenced by WSESWrapperBase().
int WSESWrapperBase::setDetectorRegion (int index, const void * value) [protected]
Setter for the detector_region property. This will set up a new ROI (Region of Interest) for the acquisition. The values in the detector region will be validated through a call to the GDS_CheckRegion() function.
Parameters:
[in] index Not used.
[in] value A pointer to a SESWrapperNS::DetectorRegion structure.
Returns:
Allways returns WError::ERR_OK.
Definition at line 907 of file wseswrapperbase.cpp.
References SESWrapperNS::WDetectorRegion::adcMode_, WError::ERR_OK, SESWrapperNS::WDetectorRegion::firstXChannel_, SESWrapperNS::WDetectorRegion::firstYChannel_, WSESInstrument::GDS_SetGlobalDetector, SESWrapperNS::WDetectorRegion::lastXChannel_, SESWrapperNS::WDetectorRegion::lastYChannel_, and SESWrapperNS::WDetectorRegion::slices_.
Referenced by WSESWrapperBase().
int WSESWrapperBase::setElementSet (int index, const void * value) [protected]
Setter for the element_set property.
Parameters:
[in] index Must be set to -1. Values between 0 and element_set_count - 1 are index for future use.
[in] value A null-terminated string that specifies the name of the new element set.
Returns:
WError::ERR_NO_INSTRUMENT if WSESWrapperMain::loadInstrument() has not been called, WError::ERR_INCORRECT_ELEMENT_SET if the given element set is not available, otherwise WError::ERR_OK.
Definition at line 944 of file wseswrapperbase.cpp.
References WError::ERR_INCORRECT_ELEMENT_SET, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, and WSESInstrument::GDS_SetElementSet.
Referenced by WSESWrapperBase().
int WSESWrapperBase::setInstrumentLibrary (int index, const void * value) [protected]
Setter for the instrument_library property. Always unloads the current library and opens the new one if it has been specified. A NULL string simply unloads the current library. This function does not call GDS_Finalize() before unloading. That responsibility falls on the calling application.
Parameters:
[in] index Not used.
[in] value A null-terminated C string that contains the name of the instrument library.
Returns:
Returns WError::ERR_OK if successfull, otherwise WError::ERR_LOAD_LIBRARY.
Definition at line 849 of file wseswrapperbase.cpp.
References WError::ERR_LOAD_LIBRARY, WError::ERR_OK, WSESInstrument::load(), and WSESInstrument::unload().
Referenced by WSESWrapperBase().
int WSESWrapperBase::setLensMode (int index, const void * value) [protected]
Setter for the element_set property. This function reloads the pass energy list when successful. This requires updates for the pass energy lists for the calling application.
Parameters:
[in] index Must be set to -1. Values between 0 and element_set_count - 1 are index for future use.
[in] value A null-terminated string that specifies the name of the new lens mode.
Returns:
WError::ERR_NO_INSTRUMENT if WSESWrapperMain::loadInstrument() has not been called, WError::ERR_INCORRECT_LENS_MODE if the given lens mode is not available, otherwise WError::ERR_OK.
Definition at line 963 of file wseswrapperbase.cpp.
References WError::ERR_INCORRECT_LENS_MODE, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, and WSESInstrument::GDS_SetLensMode.
Referenced by WSESWrapperBase().
int WSESWrapperBase::setLibWorkingDir (int index, const void * value) [protected]
Setter for the lib_working_dir property. Changes the working directory for the library.
Parameters:
[in] index Not used.
[in] value A null-terminated C string that contains the path to the new working directory.
Returns:
Always returns WError::ERR_OK.
Definition at line 818 of file wseswrapperbase.cpp.
References WError::ERR_INVALID_DIR, and WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::setPassEnergy (int index, const void * value) [protected]
Setter for the pass_energy property. If the pass energy to set is taken from a list of pass energies, make sure to update that list after modifying the lens mode and before calling this function.
Parameters:
[in] index Must be set to -1. Values between 0 and element_set_count - 1 are index for future use.
[in] value A pointer to a double (8-byte floating point).
Returns:
WError::ERR_NO_INSTRUMENT if WSESWrapperMain::loadInstrument() has not been called, WError::ERR_INCORRECT_PASS_ENERGY if the given pass energy is not available, otherwise WError::ERR_OK.
Definition at line 985 of file wseswrapperbase.cpp.
References WError::ERR_INCORRECT_PASS_ENERGY, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, WSESInstrument::GDS_GetCurrPassEnergy, and WSESInstrument::GDS_SetPassEnergy.
Referenced by WSESWrapperBase().
int WSESWrapperBase::setRegionName (int index, const void * value) [protected]
Setter for the region_name property.
Parameters:
[in] index Not used.
[in] value A null-terminated C string that specifies the region name. The name is limited to 32 characters, including the null character.
Returns:
Always returns WError::ERR_OK.
Definition at line 1122 of file wseswrapperbase.cpp.
References WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::setResetDataBetweenIterations (int index, const void * value) [protected]
Setter for the reset_data_between_iterations property.
Parameters:
[in] index Not used.
[in] value A pointer to a 1-byte boolean.
Returns:
Always returns WError::ERR_OK.
Definition at line 1151 of file wseswrapperbase.cpp.
References WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::setTempFileName (int index, const void * value) [protected]
Setter for the temp_file_name property.
Parameters:
[in] index Not used.
[in] value A null-terminated C string that specifies the name of the temporary file created during acquisition.
Returns:
Always returns WError::ERR_OK.
Definition at line 1137 of file wseswrapperbase.cpp.
References WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::setUseBindingEnergy (int index, const void * value) [protected]
Setter for the use_binding_energy property.
Warning:
If you set this to true, you must also set the excitation energy.
Parameters:
[in] index Not used.
[in] value A pointer to a 1-byte boolean.
Returns:
Always returns WError::ERR_OK.
Definition at line 1088 of file wseswrapperbase.cpp.
References WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::setUseDetector (int index, const void * value) [protected]
Setter for the use_detector property. Modify this to toggle the use of the detector. Can be used in combination with the use_external_io property.
Parameters:
[in] index Not used.
[in] value A pointer to a 1-byte boolean.
Returns:
Always returns WError::ERR_OK.
Definition at line 1105 of file wseswrapperbase.cpp.
References WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::setUseExternalIO (int index, const void * value) [protected]
Setter for the use_external_io property. Modify this to toggle the use of the external I/O card, if present.
Parameters:
[in] index Not used.
[in] value A pointer to a 1-byte boolean.
Returns:
Always returns WError::ERR_OK.
Definition at line 1039 of file wseswrapperbase.cpp.
References WError::ERR_OK.
Referenced by WSESWrapperBase().
int WSESWrapperBase::setUseSpin (int index, const void * value) [protected]
Setter for the use_spin property. If there are no spin detectors installed, this function returns WError::ERR_NOT_APPLICABLE.
Parameters:
[in] index Specifies which spin detector being queried. The value ranges between 1 and the number of available spin detectors. Which spin detector belongs to what index depends on the system configuration.
[out] value A pointer to a 1-byte boolean.
Returns:
WError::ERR_OK if a spin detector is found at index index.
Definition at line 1057 of file wseswrapperbase.cpp.
References WError::ERR_INDEX, WError::ERR_NO_INSTRUMENT, WError::ERR_NOT_APPLICABLE, WError::ERR_OK, WSESInstrument::GDS_GetOption, and WSESInstrument::GDS_SetOption.
Referenced by WSESWrapperBase().
void WSESWrapperBase::splitSESList (const char * buffer, int bufferSize, NameVector & result) [protected]
Helper function to split strings obtained as lists from calls to SESInstrument functions.
Parameters:
[in] buffer The null-terminated string containing the elements to be split. Each element is assumed to be wrapped between quotation marks ("), and separated with space (e.g. '"element 1" "element 2" "element 3"').
[in] bufferSize The maximum size of the buffer, used as an extra security measure in case the string lacks the null termination.
[out] result a string vector containing the split elements.
Definition at line 1281 of file wseswrapperbase.cpp.
Referenced by loadElementNames(), loadElementSets(), loadLensModes(), and loadPassEnergies().
The documentation for this class was generated from the following files:
C:/Development/svn/seswrapper-lib/include/wseswrapperbase.h
C:/Development/svn/seswrapper-lib/src/wseswrapperbase.cpp