SESWrapper: WError Class Reference
WError Class Reference
Maps a message index to a message string from the return values from the exported functions in SESWrapper.
#include <werror.h>
Public Types
enum ErrorCodes {
ERR_OK = 0, ERR_UNKNOWN = -1, ERR_FAIL = -2, ERR_NOT_INITIALIZED = -3,
ERR_NOT_APPLICABLE = -4, ERR_PARAMETER_NOT_FOUND = -5, ERR_INDEX = -6, ERR_INCORRECT_ELEMENT_SET = -7,
ERR_INCORRECT_LENS_MODE = -8, ERR_INCORRECT_PASS_ENERGY = -9, ERR_INCORRECT_ANALYZER_REGION = -10, ERR_INCORRECT_DETECTOR_REGION = -11,
ERR_READONLY = -12, ERR_NO_INSTRUMENT = -13, ERR_ACQUIRING = -14, ERR_INITIALIZE_FAIL = -15,
ERR_LOAD_LIBRARY = -16, ERR_OPEN_INSTRUMENT = -17, ERR_QT_RUNNING = -18, ERR_INVALID_DIR = -19,
ERR_WRONG_SIZE = -20, ERR_TIMEOUT = 8, ERR_NOT_IMPLEMENTED = 9
}
typedef std::map< int,
std::string > ErrorMessageMap
Public Member Functions
void release ()
std::string message (int errorCode)
Static Public Member Functions
static WError * instance ()
Detailed Description
Maps a message index to a message string from the return values from the exported functions in SESWrapper.
Definition at line 11 of file werror.h.
Member Enumeration Documentation
enum WError::ErrorCodes
This enumerator contains the return codes from the exported functions. Errors are represented by negative numbers, whereas positive values indicate warnings. Success is always indicated by 0 (NULL).
See also:
gErrors
Enumerator:
ERR_OK
Normal return code indicating success
ERR_UNKNOWN
Unknown error
ERR_FAIL
Operation failed
ERR_NOT_INITIALIZED
Library has not been properly initialized
ERR_NOT_APPLICABLE
Property or data parameter access not applicable (e.g. attempted to write to a read-only property)
ERR_PARAMETER_NOT_FOUND
Parameter string was not found
ERR_INDEX
Index out-of-range
ERR_INCORRECT_ELEMENT_SET
The selected element set could not be set
ERR_INCORRECT_LENS_MODE
The selected lens mode is not available
ERR_INCORRECT_PASS_ENERGY
The selected pass energy is not available
ERR_INCORRECT_ANALYZER_REGION
Error in analyzer region settings
ERR_INCORRECT_DETECTOR_REGION
Error in detector region settings
ERR_READONLY
Attempted to access a read-only variable or data parameter
ERR_NO_INSTRUMENT
No instrument is loaded (see WRP_LoadInstrument)
ERR_ACQUIRING
Acquisition in progress
ERR_INITIALIZE_FAIL
Error in call to function GDS_Initialize()
ERR_LOAD_LIBRARY
Could not load the instrument library
ERR_OPEN_INSTRUMENT
Could not open the instrument configuration file
ERR_QT_RUNNING
QT is running
ERR_INVALID_DIR
Invalid SES directory
ERR_WRONG_SIZE
Wrong parameter size
ERR_TIMEOUT
Operation timed out
ERR_NOT_IMPLEMENTED
Function has not been implemented
Definition at line 23 of file werror.h.
Member Function Documentation
WError * WError::instance () [static]
Returns the address of the WError instance. If this is the first call to this function, a new instance is created. The reference counter is always incremented, and all calls to this function must end with a corresponding call to the release() function for a proper deallocation of the singleton when closing the library.
See also:
release()
Definition at line 77 of file werror.cpp.
Referenced by WSESWrapperBase::WSESWrapperBase().
std::string WError::message (int errorCode)
Extracts the error message based on errorCode.
Parameters:
[in] errorCode An error code previously returned from a function. If no error with this code is found, the resulting string is "Unknown error".
Returns:
A string describing the error.
Definition at line 61 of file werror.cpp.
Referenced by WSESWrapperBase::getLibError().
void WError::release ()
Releases the reference to the WError singleton. This function must be called in combination with the instance() function for proper decrement of the reference counter and deallocation when closing the SESWrapper library.
See also:
instance()
Definition at line 94 of file werror.cpp.
Referenced by WSESWrapperBase::~WSESWrapperBase().
The documentation for this class was generated from the following files:
C:/Development/svn/seswrapper-lib/include/werror.h
C:/Development/svn/seswrapper-lib/src/werror.cpp