SESWrapper: WLibrary Class Reference
WLibrary Class Reference
This is a generic class for importing shared libraries dynamically.
Public Member Functions
WLibrary ()
virtual ~WLibrary ()
virtual bool load (const char *fileName)
virtual void unload ()
bool isLoaded () const
int path (char *buffer, int size) const
void * import (const char *functionName)
Protected Attributes
WLibrary_P * p_
Detailed Description
This is a generic class for importing shared libraries dynamically.
It should be subclassed to include the C functions exported from the library it contains. Each function will then be added as a callback function within the subclass.
Definition at line 56 of file wlibrary.h.
Constructor & Destructor Documentation
WLibrary::WLibrary ()
Constructs a WLibrary object.
Definition at line 31 of file wlibrary.cpp.
WLibrary::~WLibrary () [virtual]
Destroys the WLibrary object. If the contained library was loaded, it is first unloaded.
Definition at line 39 of file wlibrary.cpp.
References unload().
Member Function Documentation
void * WLibrary::import (const char * functionName)
Imports a function from the contained library.
Parameters:
[in] functionName A string specifying the name of the function to be imported.
Returns:
The address of the imported function. This should be type cast to the appropriate function pointer type from the current void* type. If the import fails, the function returns 0.
See also:
SciCoreNS::import()
Definition at line 117 of file wlibrary.cpp.
bool WLibrary::isLoaded () const
Returns:
true if a library is loaded, otherwise false.
Definition at line 85 of file wlibrary.cpp.
Referenced by WSESWrapperMain::finalize(), WSESWrapperBase::getInstrumentStatus(), WSESWrapperMain::initialize(), and WSESWrapperMain::stopAcquisition().
bool WLibrary::load (const char * fileName) [virtual]
Loads a library. This function can be reimplemented by a subclass to also resolve the exported functions available in the library.
Parameters:
[in] fileName The name (including path if needed) of the library to be loaded.
Returns:
true if successful, otherwise false.
Reimplemented in WSESInstrument.
Definition at line 53 of file wlibrary.cpp.
References unload().
Referenced by WSESInstrument::load().
int WLibrary::path (char * buffer, int size) const
Queries the path and name of the currently loaded library. The buffer parameter can be NULL if only the required buffer length is requested.
Parameters:
[in] buffer The buffer that will contain the path. Can be NULL.
[in] size The size of buffer.
Returns:
the length of the path string.
Definition at line 99 of file wlibrary.cpp.
void WLibrary::unload () [virtual]
Unloads the library and clears the internal variables. If no library has been loaded, this function returns immediately.
Reimplemented in WSESInstrument.
Definition at line 73 of file wlibrary.cpp.
Referenced by load(), WSESInstrument::unload(), and ~WLibrary().
The documentation for this class was generated from the following files:
C:/Development/svn/seswrapper-lib/include/wlibrary.h
C:/Development/svn/seswrapper-lib/src/wlibrary.cpp