SESWrapper: WSESWrapperMain Class Reference
WSESWrapperMain Class Reference
Public Types
typedef WVariable
< WSESWrapperMain > DataParameter
typedef std::pair< std::string,
DataParameter > DataParameterKeyValue
typedef std::map< std::string,
DataParameter > DataParameterMap
Public Member Functions
void release ()
int references () const
bool isInitialized ()
int initialize (void *)
int finalize ()
int getProperty (const char *name, int index, void *value, int &size)
int getProperty (const char *name, int index, void *value)
int setProperty (const char *name, int index, const void *value)
int validate (const char *elementSet, const char *lensMode, double passEnergy, double kineticEnergy)
int resetHW ()
int testHW ()
int loadInstrument (const char *fileName)
int saveInstrument (const char *fileName)
int zeroSupplies ()
int getBindingEnergy (double *bindingEnergy)
int setBindingEnergy (const double bindingEnergy)
int getKineticEnergy (double *kineticEnergy)
int setKineticEnergy (const double kineticEnergy)
int getExcitationEnergy (double *excitationEnergy)
int setExcitationEnergy (const double excitationEnergy)
int getElementVoltage (const char *elementName, double *voltage)
int setElementVoltage (const char *element, const double voltage)
int checkAnalyzerRegion (SESWrapperNS::AnalyzerRegion *analyzerRegion, int *steps, double *time_ms, double *minEnergyStep_eV)
int initAcquisition (const bool blockPointReady, const bool blockRegionReady)
int startAcquisition ()
int stopAcquisition ()
int getAcquiredData (const char *name, int index, void *data, int &size)
int waitForPointReady (int timeout_ms)
int waitForRegionReady (int timeout_ms)
int continueAcquisition ()
int openGui (const char *name)
int loadLensTable (const char *lensmode, const char *filePath)
int setupDetector (SESWrapperNS::PDetectorRegion detectorRegion)
int checkProperty (const char *parameter, int size)
int parameterType (const char *parameter)
int getAcqChannels (int index, void *data, int &size)
int getAcqSlices (int index, void *data, int &size)
int getAcqIterations (int index, void *data, int &size)
int getAcqIntensityUnit (int index, void *data, int &size)
int getAcqChannelUnit (int index, void *data, int &size)
int getAcqSliceUnit (int index, void *data, int &size)
int getAcqSpectrum (int index, void *data, int &size)
int getAcqImage (int index, void *data, int &size)
int getAcqSlice (int index, void *data, int &size)
int getAcqChannelScale (int index, void *data, int &size)
int getAcqSliceScale (int index, void *data, int &size)
int getAcqRawImage (int index, void *data, int &size)
int getAcqCurrentStep (int index, void *data, int &size)
int getAcqElapsedTime (int index, void *data, int &size)
int getAcqIOPorts (int index, void *data, int &size)
int getAcqIOSize (int index, void *data, int &size)
int getAcqIOIterations (int index, void *data, int &size)
int getAcqIOUnit (int index, void *data, int &size)
int getAcqIOScale (int index, void *data, int &size)
int getAcqIOSpectrum (int index, void *data, int &size)
int getAcqIOData (int index, void *data, int &size)
int getAcqIOPortName (int index, void *data, int &size)
int getAcqCurrentPoint (int index, void *value, int &size)
int getAcqPointIntensity (int index, void *value, int &size)
int getAcqChannelIntensity (int index, void *value, int &size)
Static Public Member Functions
static WSESWrapperMain * instance ()
Detailed Description
This is the main class for the SESWrapper library.
All exported functions uses a global instance of WSESWrapperMain
Definition at line 9 of file wseswrappermain.h.
Member Function Documentation
int WSESWrapperMain::checkAnalyzerRegion (SESWrapperNS::AnalyzerRegion * analyzerRegion, int * steps, double * time_ms, double * minEnergyStep_eV)
Validates the current analyzer region.
In addition to validating the region, this function also returns the number of steps (for swept mode acquisitions) that will be taken, the minimum dwell time per step (ms), and the smallest step size (eV).
Parameters:
[out] analyzerRegion A pointer to a SESWrapperNS::AnalyzerRegion struct that will be filled with validated values.
[out] steps The number of steps that will be taken for a swept mode acquisition.
[out] time_ms The estimated acquisition time (in ms) for one iteration.
[out] minEnergyStep_eV The minimum step size (in eV) for swept mode acquisition.
Returns:
WError::ERR_NO_INSTRUMENT if loadInstrument() has not been called, WError::ERR_INCORRECT_ANALYZER_REGION if an error was detected in the analyzer region, otherwise WError::ERR_OK.
Definition at line 654 of file wseswrappermain.cpp.
References SESWrapperNS::WAnalyzerRegion::centerEnergy_, SESWrapperNS::WAnalyzerRegion::dwellTime_, SESWrapperNS::WAnalyzerRegion::energyStep_, WError::ERR_INCORRECT_ANALYZER_REGION, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, SESWrapperNS::WAnalyzerRegion::fixed_, WSESInstrument::GDS_CheckRegion, SESWrapperNS::WAnalyzerRegion::highEnergy_, and SESWrapperNS::WAnalyzerRegion::lowEnergy_.
int WSESWrapperMain::checkProperty (const char * name, int size)
Check if a property exists and has the expected size.
Returns:
WError
Definition at line 954 of file wseswrappermain.cpp.
References WError::ERR_OK, WError::ERR_WRONG_SIZE, and getProperty().
int WSESWrapperMain::continueAcquisition ()
Releases the acquisition thread after a blocked point or region. Blocking points or regions is done by setting blockPointReady or blockRegionReady to true in the initAcquisition() member function call.
See also:
waitForPointReady(), waitForRegionReady() initAcquisition(), startAcquisition(), stopAcquisition()
Definition at line 894 of file wseswrappermain.cpp.
References WError::ERR_OK, WEvent::reset(), and WEvent::set().
int WSESWrapperMain::finalize ()
Aborts any currently executing acquisition, and closes the SESInstrument.dll library.
If initialization of SESWrapper was made by a call to initialize(), this member function must be called before closing the library. If SESWrapper successfully made the initialization on startup, this member function does not need to be called, as that is then done automatically when the library closes.
Returns:
Always returns WError::ERR_OK.
See also:
initialize()
Definition at line 228 of file wseswrappermain.cpp.
References WError::ERR_OK, WSESInstrument::GDS_Finalize, WLibrary::isLoaded(), WEvent::set(), and WSESInstrument::unload().
int WSESWrapperMain::getAcqChannelIntensity (int index, void * data, int & size)
Getter for the acq_channel_intensity variable. This extracts the intensity from all slices of channel index. If index is negative or outside the energy range of the region, the function succeedes with data set to 0.
Parameters:
[in] index The point/channel to query. This can be negative or greater than the number of channels. An index of 0 corresponds to the first spectrum channel.
[out] data A pointer to a double array that will be modified to the number of millisecondes elapsed since the last call of startAcquisition(). The array should be large enough to contain acq_slices slices.
[in,out] size Modified to acq_slices.
Returns:
WError::ERR_OK on success, WError::ERR_NOT_INITIALIZED if no acquisition has been performed,
Definition at line 1591 of file wseswrappermain.cpp.
References WError::ERR_NOT_INITIALIZED, and WError::ERR_OK.
int WSESWrapperMain::getAcqChannels (int index, void * data, int & size)
Getter for the acq_channels variable. If no acquisition has been performed, the number of channels is 0.
Parameters:
[in] index Not used.
[out] data A pointer to a 32-bit integer that will be modified with the number of energy channels in the acquired spectrum.
[in,out] size Not used.
Returns:
Always returns WError::ERR_OK.
Definition at line 996 of file wseswrappermain.cpp.
References WError::ERR_OK.
int WSESWrapperMain::getAcqChannelScale (int index, void * data, int & size)
Getter for the acq_channel_scale variable. Defines an array of doubles where each element corresponds to an energy channel. The scale is always in kinetic energy.
Parameters:
[in] index Not used.
[out] data An array of doubles that will be filled with the channel scale. Can be 0 (NULL).
[in,out] size If data is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array.
Returns:
WError::ERR_FAIL if no acquisition has been performed, otherwise WError::ERR_OK.
Definition at line 1208 of file wseswrappermain.cpp.
References WError::ERR_FAIL, and WError::ERR_OK.
int WSESWrapperMain::getAcqChannelUnit (int index, void * data, int & size)
Getter for the acq_channel_unit variable. The channel unit is a string of up to 32 characters (including the null termination) defining the unit of the energy axis in the acquired spectrum.
Parameters:
[in] index Not used.
[out] data A char* buffer to be filled with the channel unit. Can be 0 (NULL).
[in,out] size If data is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array.
Returns:
WError::ERR_FAIL if no acquisition has been performed, otherwise WError::ERR_OK.
Definition at line 1084 of file wseswrappermain.cpp.
References WError::ERR_FAIL, and WError::ERR_OK.
int WSESWrapperMain::getAcqCurrentPoint (int index, void * data, int & size)
Getter for the acq_current_point variable. The point is only useful for swept mode acquisitions, and has a negative value until the acquisition has entered valid channels during the acquisition. It is important to use the waitForPointReady() function to make sure no data points are missed.
Parameters:
[in] index Not used.
[out] data A pointer to a 32-bit unsigned integer that shows the latest step index during a swept mode acquisition. This value is undefined until waitForPointReady() returns success, and remains negative until the acquisition has reached a valid channel.
[in,out] size Not used.
Returns:
Always returns WError::ERR_OK.
Definition at line 1538 of file wseswrappermain.cpp.
References WError::ERR_OK.
int WSESWrapperMain::getAcqCurrentStep (int index, void * data, int & size)
Getter for the acq_current_step variable. Use this to obtain the current step in a swept acquisition.
Parameters:
[in] index Not used.
[out] data A pointer to a 32-bit integer that will be set to the current step.
[in,out] size Not used.
Returns:
WError::ERR_FAIL if no acquisition has been performed, otherwise WError::ERR_OK.
Definition at line 1292 of file wseswrappermain.cpp.
References WError::ERR_FAIL, and WError::ERR_OK.
int WSESWrapperMain::getAcqElapsedTime (int index, void * data, int & size)
Getter for the acq_elapsed_time variable. This can be used to evaluate how many milliseconds have passed since the last call of startAcquisition().
Parameters:
[in] index Not used.
[out] data A pointer to a 32-bit unsigned integer that will be modified to the number of millisecondes elapsed since the last call of startAcquisition().
[in,out] size Not used.
Returns:
Always returns WError::ERR_OK.
Definition at line 1316 of file wseswrappermain.cpp.
References WError::ERR_OK.
int WSESWrapperMain::getAcqImage (int index, void * data, int & size)
Getter for the acq_image variable.
Parameters:
[in] index Not used.
[out] data An array of doubles that will be filled with the acquired image. Can be 0 (NULL).
[in,out] size If data is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array.
Definition at line 1155 of file wseswrappermain.cpp.
References WError::ERR_FAIL, and WError::ERR_OK.
int WSESWrapperMain::getAcqIntensityUnit (int index, void * data, int & size)
Getter for the acq_intensity_unit variable. The intensity unit is a string of up to 32 characters (including the null termination) defining the unit of the intensity axis in the acquired spectrum.
Parameters:
[in] index Not used.
[out] data A char* buffer to be filled with the intensity unit. Can be 0 (NULL).
[in,out] size If data is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array.
Returns:
WError::ERR_FAIL if no acquisition has been performed, otherwise WError::ERR_OK.
Definition at line 1058 of file wseswrappermain.cpp.
References WError::ERR_FAIL, and WError::ERR_OK.
int WSESWrapperMain::getAcqIOData (int index, void * data, int & size)
Getter for the acq_io_data variable. Extracts all External I/O data acquired.
Parameters:
[in] index Not used.
[out] data An array of doubles that will be filled with the spectra acquired from the External I/O ports. Can be 0 (NULL).
[in,out] size If data is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array (acq_io_ports * acq_io_size).
Returns:
WError::ERR_FAIL if External I/O is not available or if no acquisition has been initialized, otherwise WError::ERR_OK.
Definition at line 1482 of file wseswrappermain.cpp.
References WError::ERR_FAIL, and WError::ERR_OK.
int WSESWrapperMain::getAcqIOIterations (int index, void * data, int & size)
Getter for the acq_io_iterations variable. Used with External I/O measurements to query the number of iterations that have elapsed since the last call of initAcquisition().
Parameters:
[in] index Not used.
[out] data A pointer to a 32-bit integer the will be modified to show the number of iterations.
[in,out] size Not used.
Returns:
WError::ERR_FAIL if External I/O is not available or if no acquisition has been initialized, otherwise WError::ERR_OK.
Definition at line 1384 of file wseswrappermain.cpp.
References WError::ERR_FAIL, and WError::ERR_OK.
int WSESWrapperMain::getAcqIOPortName (int index, void * data, int & size)
Getter for the acq_io_port_name variable. Obtains the name of one port in the External I/O port list.
Parameters:
[in] index The index of the port that will be queried. Must be between 0 and acq_io_ports.
[out] data A char* buffer to be filled with the name of the External I/O port specified by index. Can be 0 (NULL).
[in,out] size If data is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array.
Returns:
WError::ERR_FAIL if External I/O is not available or if no acquisition has been initialized, WError::ERR_INDEX if index is out-of-bounds, otherwise WError::ERR_OK.
Definition at line 1510 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_INDEX, and WError::ERR_OK.
int WSESWrapperMain::getAcqIOPorts (int index, void * data, int & size)
Getter for the acq_io_ports variable. Use this to obtain the number of External I/O-ports.
Parameters:
[in] index Not used.
[out] data A pointer to a 32-bit integer that will be modified with the number of External I/O-ports.
[in,out] size Not used.
Returns:
WError::ERR_FAIL if External I/O is not available or if no acquisition has been initialized, otherwise WError::ERR_OK.
Definition at line 1336 of file wseswrappermain.cpp.
References WError::ERR_FAIL, and WError::ERR_OK.
int WSESWrapperMain::getAcqIOScale (int index, void * data, int & size)
Getter for the acq_io_scale variable. Defines an array of doubles where each element corresponds to an External I/O step.
Parameters:
[in] index Not used.
[out] data An array of doubles that will be filled with the External I/O scale. Can be 0 (NULL).
[in,out] size If data is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array.
Returns:
WError::ERR_FAIL if External I/O is not available or if no acquisition has been initialized, otherwise WError::ERR_OK.
Definition at line 1432 of file wseswrappermain.cpp.
References WError::ERR_FAIL, and WError::ERR_OK.
int WSESWrapperMain::getAcqIOSize (int index, void * data, int & size)
Getter for the acq_io_size variable. This is used with the External I/O mechanizm, where the data is collected from a number of ports from e.g. a DAQ card. This variable show the size of one spectrum.
Parameters:
[in] index Not used.
[out] data A pointer to a 32-bit integer that will be modified with the number of channels in one External I/O spectrum.
[in,out] size Not used.
Returns:
WError::ERR_FAIL if External I/O is not available or if no acquisition has been initialized, otherwise WError::ERR_OK.
Definition at line 1360 of file wseswrappermain.cpp.
References WError::ERR_FAIL, and WError::ERR_OK.
int WSESWrapperMain::getAcqIOSpectrum (int index, void * data, int & size)
Getter for the acq_io_spectrum variable. Extracts one spectrum from one of the External I/O ports. To extract all ports at once, use the acq_io_data variable instead.
Parameters:
[in] index The index of the port to be queried. Must be between 0 and acq_io_ports - 1.
[out] data An array of doubles that will be filled with the data acquired from External I/O port index. Can be 0 (NULL).
[in,out] size If data is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array.
Returns:
WError::ERR_FAIL if External I/O is not available or if no acquisition has been initialized, WError::ERR_INDEX if index is out-of-bounds, otherwise WError::ERR_OK.
Definition at line 1456 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_INDEX, and WError::ERR_OK.
int WSESWrapperMain::getAcqIOUnit (int index, void * data, int & size)
Getter for the acq_io_unit variable. The External I/O unit is a string of up to 32 characters (including the null termination) defining the unit of the External I/O spectrum.
Parameters:
[in] index Not used.
[out] data A char* buffer to be filled with the External I/O unit. Can be 0 (NULL).
[in,out] size If data is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array.
Returns:
WError::ERR_FAIL if External I/O is not available or if no acquisition has been initialized, otherwise WError::ERR_OK.
Definition at line 1409 of file wseswrappermain.cpp.
References WError::ERR_FAIL, and WError::ERR_OK.
int WSESWrapperMain::getAcqIterations (int index, void * data, int & size)
Getter for the acq_iterations variable. The number of iterations is incremented by 1 when startAcquisition() is called. The counter is reset when initAcquisition() is called. If no acquisition has been performed, the number of iterations is 0.
Parameters:
[in] index Not used.
[out] data A pointer to a 32-bit integer that will be modified with the number of iterations that have elapsed since the last call of initAcquisition().
[in,out] size Not used.
Returns:
Always returns WError::ERR_OK.
Definition at line 1037 of file wseswrappermain.cpp.
References WError::ERR_OK.
int WSESWrapperMain::getAcqPointIntensity (int index, void * data, int & size)
Getter for the acq_point_intensity variable. This extracts the intensity from channel index. If index is negative or outside the energy range of the region, the function succeedes with data set to 0.
Parameters:
[in] index The point/channel to query. This can be negative or greater than the number of channels. An index of 0 corresponds to the first spectrum channel.
[out] data A pointer to a double that will be modified to the number of millisecondes elapsed since the last call of startAcquisition().
[in,out] size Not used.
Returns:
WError::ERR_OK on success, WError::ERR_NOT_INITIALIZED if no acquisition has been performed,
Definition at line 1558 of file wseswrappermain.cpp.
References WError::ERR_NOT_INITIALIZED, and WError::ERR_OK.
int WSESWrapperMain::getAcqRawImage (int index, void * data, int & size)
Getter for the acq_raw_image variable. Defines a byte array that will span the data in one frame taken from the detector. If the detector is not based on frames/images, this variable will not be available.
One frame usually has a size of xChannels * yChannels * byteSize, where xChannels and yChannels can be obtained from the detector_info property. The byteSize variable is the number of bytes used per element in the image, which is 1 for 8-bit images, or 2 for 16-bit images. To get the byteSize, call this function with data set to 0 (NULL) and then divide the size parameter obtained with xChannels * yChannels.
Parameters:
[in] index Not used.
[out] data An array of bytes (unsigned char*) that will be filled with a snapshot of the detector image. Can be 0 (NULL).
[in,out] size If data is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array (xChannels * yChannels * byteSize).
Returns:
WError::ERR_NOT_INITIALIZED if the wrapped library is not properly initialized, WError::ERR_FAIL if the raw image could not be obtained (possibly because the detector does not support 2D-frames), otherwise WError::ERR_OK on success.
See also:
WSESWrapperBase::getDetectorInfo()
Definition at line 1263 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_INCORRECT_DETECTOR_REGION, WError::ERR_NOT_INITIALIZED, WError::ERR_OK, and WSESInstrument::GDS_GetRawImage.
int WSESWrapperMain::getAcqSlice (int index, void * data, int & size)
Getter for the acq_slice variable. This function can be called to obtain one slice from the spectrum image.
Parameters:
[in] index Specifies which slice to extract from the spectrum. Must be between 0 and the number of slices - 1.
[out] data An array of doubles that will be filled with the elements of the slice. Can be 0 (NULL).
[in,out] size If data is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array.
Returns:
WError::ERR_FAIL if no acquisition has been performed, WError::ERR_INDEX if index is out-of-bounds, otherwise WError::ERR_OK.
Definition at line 1182 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_INDEX, and WError::ERR_OK.
int WSESWrapperMain::getAcqSlices (int index, void * data, int & size)
Getter for the acq_slices variable. If no acquisition has been performed, the number of slices is 0.
Parameters:
[in] index Not used.
[out] data A pointer to a 32-bit integer that will be modified with the number of slices in the acquired spectrum.
[in,out] size Not used.
Returns:
Always returns WError::ERR_OK.
Definition at line 1015 of file wseswrappermain.cpp.
References WError::ERR_OK.
int WSESWrapperMain::getAcqSliceScale (int index, void * data, int & size)
Getter for the acq_slice_scale variable. Defines an array of doubles where each element corresponds to one position in the Y axis.
Parameters:
[in] index Not used.
[out] data An array of doubles that will be filled with the Y axis scale (the slices). Can be 0 (NULL).
[in,out] size If data is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array.
Returns:
WError::ERR_FAIL if no acquisition has been performed, otherwise WError::ERR_OK.
Definition at line 1230 of file wseswrappermain.cpp.
References WError::ERR_FAIL, and WError::ERR_OK.
int WSESWrapperMain::getAcqSliceUnit (int index, void * data, int & size)
Getter for the acq_slice_unit variable. The slice unit is a string of up to 32 characters (including the null termination) defining the unit of the Y axis in the acquired spectrum image.
Parameters:
[in] index Not used.
[out] data A char* buffer to be filled with the channel unit. Can be 0 (NULL).
[in,out] size If data is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array.
Returns:
WError::ERR_FAIL if no acquisition has been performed, otherwise WError::ERR_OK.
Definition at line 1110 of file wseswrappermain.cpp.
References WError::ERR_FAIL, and WError::ERR_OK.
int WSESWrapperMain::getAcqSpectrum (int index, void * data, int & size)
Getter for the acq_spectrum variable. The spectrum is a vector of doubles (8-byte floating point values) with the integrated intensities of all slices.
Parameters:
[in] index Not used.
[out] data An array of doubles that will be filled with the integrated spectrum. Can be 0 (NULL).
[in,out] size If data is non-null, this parameter is assumed to contain the maximum number of elements in the buffer. After completion, size is always modified to contain the length of the resulting array.
Returns:
WError::ERR_FAIL if no acquisition has been performed, otherwise WError::ERR_OK.
Definition at line 1136 of file wseswrappermain.cpp.
References WError::ERR_FAIL, and WError::ERR_OK.
int WSESWrapperMain::getAcquiredData (const char * variable, int index, void * data, int & size)
This is a generic function for obtaining the value of acquired data or related variables. The data parameter is declared void * in order to allow any type of data to be accessed.
Parameters:
[in] variable The name of the variable to be queried.
[in] index Used to query a specific element from a variable that is stored as a vector.
[out] data Pointer to a variable that will be filled with the data specified by variable. This parameter can be 0 (NULL). In that case, size can be used to obtain the required size of data if the variable is a string or vector.
[in,out] size This parameter is used to get the size of data when the variable is a string or vector.
Returns:
WError::ERR_PARAMETER_NOT_FOUND if variable was not a valid variable name, otherwise the return code depends on the type of variable.
Definition at line 812 of file wseswrappermain.cpp.
References WError::ERR_PARAMETER_NOT_FOUND.
int WSESWrapperMain::getBindingEnergy (double * bindingEnergy)
Reads the current kinetic energy from the SESInstrument library and converts it to binding energy before returning.
Warning:
If the excitation energy has not been set before calling this function, the result is undefined.
Parameters:
[out] bindingEnergy Pointer to a double to be modified with the current binding energy.
Returns:
WError::ERR_NO_INSTRUMENT if loadInstrument() has not been called, WError::ERR_FAIL if the energy could not be read, otherwise WError::ERR_OK.
Definition at line 512 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, and WSESInstrument::GDS_GetCurrBindingEnergy.
int WSESWrapperMain::getElementVoltage (const char * elementName, double * voltage)
Reads the current voltage from analyzer element elementName.
Parameters:
[in] elementName A string specifying the name of the element to be read.
[out] voltage A pointer to a variable that will receive the voltage (in V).
Returns:
WError::ERR_NO_INSTRUMENT if loadInstrument() has not been called, WError::ERR_FAIL if the element could not be read (e.g. the element elementName does not exist), otherwise WError::ERR_OK.
Definition at line 613 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, and WSESInstrument::GDS_GetElement.
int WSESWrapperMain::getExcitationEnergy (double * excitationEnergy)
Reads the current excitation energy from the SESInstrument library.
Parameters:
[out] excitationEnergy Pointer to a double to be modified with the current excitation energy.
Returns:
WError::ERR_NO_INSTRUMENT if loadInstrument() has not been called, WError::ERR_FAIL if the energy could not be read, otherwise WError::ERR_OK.
Definition at line 579 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, and WSESInstrument::GDS_GetCurrExcitationEnergy.
int WSESWrapperMain::getKineticEnergy (double * kineticEnergy)
Reads the current kinetic energy from the SESInstrument library.
Parameters:
[out] kineticEnergy Pointer to a double to be modified with the current kinetic energy.
Returns:
WError::ERR_NO_INSTRUMENT if loadInstrument() has not been called, WError::ERR_FAIL if the energy could not be read, otherwise WError::ERR_OK.
Definition at line 544 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, and WSESInstrument::GDS_GetCurrKineticEnergy.
int WSESWrapperMain::getProperty (const char * name, int index, void * value)
This is a convenience member function that can be used when the size parameter is not required.
See also:
getProperty(const char *property, int index, void *value, int &size)
Definition at line 292 of file wseswrappermain.cpp.
References getProperty().
int WSESWrapperMain::getProperty (const char * property, int index, void * value, int & size)
This is a generic function for obtaining the value of a property. The value parameter is declared void * in order to allow any type of property to be accessed. The main requirement for all types of properties is that the value parameter is a pointer to the object containing the data of the property. All properties are defined with a getter and a setter in the WSESWrapperBase class.
Parameters:
[in] property A string specifying the property to be queried.
[in] index For those properties that are stored in arrays, this will indicate which array element is requested.
[out] value A pointer to a variable that will be given the requested property.
[in,out] size This parameter is used to get the size of value. In some cases (e.g. when the property is an array or string) this parameter specifies the number of elements. When value is 0 (NULL), size is modified to the required size of arrays/strings. When the property is a structure or number, size if not modified, and value cannot be 0.
Returns:
WError::ERR_PARAMETER_NOT_FOUND if the property was not a valid variable name, other wise the return code is dependent on the type of variable.
See also:
WSESWrapperBase, SESWrapper Library Variables
Definition at line 265 of file wseswrappermain.cpp.
References WError::ERR_NOT_INITIALIZED, WError::ERR_OK, WError::ERR_PARAMETER_NOT_FOUND, WError::ERR_WRONG_SIZE, and WSESInstrument::SC_GetProperty.
Referenced by checkProperty(), and getProperty().
int WSESWrapperMain::initAcquisition (const bool blockPointReady, const bool blockRegionReady)
Initializes an acquisition.
This function initializes an acquisition. It sets the iteration index to 0, thus creating a new acquisition. The blockPointReady and blockRegionReady parameters specifies whether acquisition should pause for each step or regin, respectively.
Parameters:
[in] blockPointReady If true, this parameter tells the acquisition thread to wait for confirmation between each step taken in a swept mode acquisition.
[in] blockRegionReady If true, this parameter tells the acquisition thread to wait for confirmation once the acquisition is finished.
Returns:
WError::ERR_NO_INSTRUMENT if loadInstrument() has not been called, WError::ERR_INCORRECT_ANALYZER_REGION if an error was detected in the analyzer region, otherwise WError::ERR_OK.
Definition at line 684 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, WSESInstrument::GDS_GetStatus, WSESInstrument::GDS_InitAcquisition, SesNS::NonOperational, WEvent::reset(), and SesNS::Running.
int WSESWrapperMain::initialize (void * reserved)
Opens the SESInstrument.dll library and imports the functions of that library.
When SESWrapper loads, it tries to load the SESInstrument library and run GDS_Initialize automatically. If successful, initialize() should not be called. However, if the SESInstrument library was not found during startup, the user needs to change the working directory to the SES software (using the lib_working_dir property) and then call initialize(). In that case, the user assumes the responsibility for calling the finalize() member function as well.
Parameters:
[in,out] reserved This parameter is reserved for future use. It must be set to 0.
Returns:
Possible return codes: WError::ERR_OK on success, WError::ERR_LOAD_LIBRARY if the instrument library could not be loaded, WError::ERR_INITIALIZE_FAIL if the initialization failed.
See also:
finalize()
Definition at line 152 of file wseswrappermain.cpp.
References WError::ERR_INITIALIZE_FAIL, WError::ERR_LOAD_LIBRARY, WError::ERR_OK, WError::ERR_QT_RUNNING, WSESInstrument::GDS_CalibrateDetector, WSESInstrument::GDS_CalibrateVoltages, WSESInstrument::GDS_ControlSupplies, WSESInstrument::GDS_DetectorInfo, WSESInstrument::GDS_Initialize, WSESInstrument::GDS_InstallElements, WSESInstrument::GDS_InstallInstrument, WSESInstrument::GDS_InstallLensModes, WSESInstrument::GDS_InstallSupplies, WSESInstrument::GDS_SetupSignals, WSESInstrument::GDS_SupplyInfo, WLibrary::isLoaded(), and WSESInstrument::load().
WSESWrapperMain * WSESWrapperMain::instance () [static]
Creates a WSESWrapperMain object or returns the existing one.
Returns:
Returns the WSESWrapperMain singleton object.
Definition at line 90 of file wseswrappermain.cpp.
bool WSESWrapperMain::isInitialized ()
This method can be used to get information about the initialization status of SESWrapper.
Returns:
true if the library is initialized.
See also:
initialize()
Definition at line 131 of file wseswrappermain.cpp.
int WSESWrapperMain::loadInstrument (const char * fileName)
Loads an instrument configuration file. The SESInstrument library must have been initialized before calling this member function.
Parameters:
[in] fileName The name of the configuration file. It is possible to use an absolute or relative path. If filename pointer is zero, the instrument file name is read from the ini\Ses.ini file in current working directory.
Returns:
WError::ERR_NOT_INITIALIZED if initialize() has not been called, WError::ERR_OPEN_INSTRUMENT if the file could not be opened, WError::ERR_FAIL if the instrument configuration is corrupted, otherwise WError::ERR_OK.
Definition at line 396 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_NOT_INITIALIZED, WError::ERR_OPEN_INSTRUMENT, WSESInstrument::GDS_GetDetectorInfo, WSESInstrument::GDS_GetGlobalDetector, WSESInstrument::GDS_GetInstrumentInfo, WSESInstrument::GDS_LoadInstrument, WSESWrapperBase::loadElementNames(), WSESWrapperBase::loadElementSets(), WSESWrapperBase::loadLensModes(), and WSESWrapperBase::loadPassEnergies().
int WSESWrapperMain::parameterType (const char * name)
Queries the type of a property or data parameter by searching for name.
Returns:
One of the types defined in WVariable.
Definition at line 971 of file wseswrappermain.cpp.
int WSESWrapperMain::references () const
Returns:
Returns the number of references to the WSESWrapperMain instance.
Definition at line 119 of file wseswrappermain.cpp.
void WSESWrapperMain::release ()
Releases a reference of the WSESWrapper object. This function must be called the same number of times the instance() function has been called. Note that this function is not a static function (like the instance() function is).
Definition at line 104 of file wseswrappermain.cpp.
int WSESWrapperMain::resetHW ()
Resets the instrument and puts it in a default state.
Returns:
WError::ERR_FAIL if not successful, otherwise WError::ERR_OK.
Definition at line 368 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_OK, WSESInstrument::GDS_ResetInstrument, and stopAcquisition().
int WSESWrapperMain::saveInstrument (const char * fileName)
Saves an instrument configuration file. The SESInstrument library must have been initialized before calling this member function.
Parameters:
[in] fileName The name of the configuration file. It is possible to use an absolute or relative path. If filename pointer is zero, the current instrument file name is used.
Returns:
WError::ERR_NO_INSTRUMENT if no instrument has been loaded, otherwise WError::ERR_OK.
Definition at line 471 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_NO_INSTRUMENT, and WSESInstrument::GDS_SaveInstrument.
int WSESWrapperMain::setBindingEnergy (const double bindingEnergy)
Changes the binding energy.
Warning:
If the excitation energy has not been set before calling this function, the result is undefined.
Parameters:
[in] bindingEnergy The binding energy (in eV) to be set.
Returns:
WError::ERR_NO_INSTRUMENT if loadInstrument() has not been called, WError::ERR_FAIL if the energy could not be read, otherwise WError::ERR_OK.
Definition at line 528 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, and WSESInstrument::GDS_SetBindingEnergy.
int WSESWrapperMain::setElementVoltage (const char * elementName, const double voltage)
Changes the voltage of analyzer element elementName.
Parameters:
[in] elementName A string specifying the name of the element to be modified.
[in] voltage The new voltage (in V).
Returns:
WError::ERR_NO_INSTRUMENT if loadInstrument() has not been called, WError::ERR_FAIL if the element voltage could not be set (e.g. the element elementName does not exist), otherwise WError::ERR_OK.
Definition at line 631 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, and WSESInstrument::GDS_SetElement.
int WSESWrapperMain::setExcitationEnergy (const double excitationEnergy)
Changes the excitation energy.
Parameters:
[in] excitationEnergy The excitation energy (in eV) to be set.
Returns:
WError::ERR_NO_INSTRUMENT if loadInstrument() has not been called, WError::ERR_FAIL if the energy could not be changed, otherwise WError::ERR_OK.
Definition at line 594 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, and WSESInstrument::GDS_SetExcitationEnergy.
int WSESWrapperMain::setKineticEnergy (const double kineticEnergy)
Changes the kinetic energy. Use this member function when initAcquisition() and startAcquisition() is not going to be called, e.g. when controlling the Scienta analyzer with an external, third-party detector to make measurements.
Parameters:
[in] kineticEnergy The kinetic energy (in eV) to be set.
Returns:
WError::ERR_NO_INSTRUMENT if loadInstrument() has not been called, WError::ERR_FAIL if the energy could not be read, otherwise WError::ERR_OK.
Definition at line 562 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, and WSESInstrument::GDS_SetKineticEnergy.
int WSESWrapperMain::setProperty (const char * property, int size, const void * value)
This is a generic function for modifying the value of a property. The value parameter is declared const void * in order to allow any type of property to be accessed.
Parameters:
[in] property A string specifying the property that will be modified.
[in] size This parameter must specify the size (in bytes) of the value argument.
[in] value A pointer to the value of the property that will be modified.
Returns:
An error code, as defined by the corresponding setter. If the property is not found and SESInstrument does not expose generic property functions SC_SetProperty or SC_SetPropertyEx, a WError::ERR_PARAMETER_NOT_FOUND code is returned.
See also:
WSESWrapperBase, SESWrapper Library Variables
Definition at line 312 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_OK, WError::ERR_PARAMETER_NOT_FOUND, WSESInstrument::SC_SetProperty, and WSESInstrument::SC_SetPropertyEx.
int WSESWrapperMain::startAcquisition ()
Starts an acquisition.
If WAnalyzerRegion::fixed_ is set to true (or 1), this will start one fixed mode acquisition. If set to false (or 0), a swept mode acquisition is started. initAcquisition() must be called the first time an acquisition will be made. After that, startAcquisition() can be called any number of times to accumulate data to the same spectrum. All data is stored in the temporary file specified by the temp_file_name property, which can later be used translate the results to e.g. an Igor format. Before calling this member function, the analyzer_region and detector_region properties should be properly prepared with correct region settings. It is possible to validate the analyzer settings by calling checkanalyzerRegion() before calling this.
The function returns immediately to allow the caller to continue working. Use waitForPointReady() and/or waitForRegionReady() if blocking is required.
Returns:
WError::ERR_NO_INSTRUMENT if loadInstrument() has not been called, WError::ERR_FAIL if the acquisition could not be started (e.g. another acquisition is already running), otherwise WError::ERR_OK.
Definition at line 742 of file wseswrappermain.cpp.
References WError::ERR_ACQUIRING, WError::ERR_FAIL, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, WSESInstrument::GDS_GetCurrSignals, WSESInstrument::GDS_GetStatus, WSESInstrument::GDS_Start, WSESInstrument::GDS_UseDetector, WSESInstrument::GDS_UseSignals, SesNS::NonOperational, WEvent::reset(), and SesNS::Running.
int WSESWrapperMain::stopAcquisition ()
Aborts the current acquisition. Can be called at any time to stop an active acquisition and set the library to an idle state.
Returns:
WError::ERR_NO_INSTRUMENT if loadInstrument() has not been called, WError::ERR_FAIL if the acquisition could not be stopped, otherwise WError::ERR_OK.
Definition at line 786 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, WSESInstrument::GDS_Stop, WLibrary::isLoaded(), WEvent::reset(), and WEvent::set().
Referenced by resetHW().
int WSESWrapperMain::testHW ()
Tests the hardware to check communication status.
Returns:
WError::ERR_FAIL if not successful, otherwise WError::ERR_OK.
Definition at line 379 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_OK, and WSESInstrument::GDS_TestCommunication.
int WSESWrapperMain::validate (const char * elementSet, const char * lensMode, double passEnergy, double kineticEnergy)
Validates the element set, lens mode, pass energy and kinetic energy (the kinetic energy is currently not checked and will thus always result in success). This member function will return WError::ERR_OK if the supplied combination of elementSet, lensMode, passEnergy and kineticEnergy is valid.
Parameters:
[in] elementSet The element set to be validated.
[in] lensMode The lens mode to be validated.
[in] passEnergy The pass energy to be validated.
[in] kineticEnergy The kinetic energy to be validated. Currently not checked.
Returns:
WError::ERR_NO_INSTRUMENT if no instrument is loaded, WError::ERR_INCORRECT_ELEMENT_SET if the given element set is invalid, WError::ERR_INCORRECT_LENS_MODE is the given lens mode is invalid, WError::ERR_INCORRECT_PASS_ENERGY if the given pass energy is not available for the given lens mode. If the validation is successful, returns WError::ERR_OK.
Definition at line 340 of file wseswrappermain.cpp.
References WError::ERR_INCORRECT_ELEMENT_SET, WError::ERR_INCORRECT_LENS_MODE, WError::ERR_INCORRECT_PASS_ENERGY, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, and WSESWrapperBase::loadPassEnergies().
int WSESWrapperMain::waitForPointReady (int timeout_ms)
Blocks execution of the callers thread until the current point has been completed during a swept mode acquisition. If timeout_ms is set to -1, there is no time-out. Do not use -1 when running fixed mode acquisitions, as there is no step taken in those cases, so there is no event that can unlock this. The WError::ERR_TIMEOUT is a warning code (error code > 0) which can be used to separate behavior from more serious errors.
Parameters:
[in] timeout_ms The number of milliseconds to wait until time-out.
Returns:
WError::ERR_NO_INSTRUMENT if loadInstrument() has not been called. Returns immediately with a WError::ERR_OK if there is no acquisition running. WError::ERR_OK is returned when the measured point has been completed. WError::ERR_TIMEOUT is returned if the function times out before comletion of the point.
See also:
continueAcquisition(), waitForPointReady(), initAcquisition(), startAcquisition(), stopAcquisition()
Definition at line 838 of file wseswrappermain.cpp.
References WError::ERR_NO_INSTRUMENT, WError::ERR_OK, WError::ERR_TIMEOUT, WSESInstrument::GDS_GetStatus, WEvent::handle(), SesNS::NonOperational, and SesNS::Running.
int WSESWrapperMain::waitForRegionReady (int timeout_ms)
Blocks execution of the callers thread until the current region has been completed. If timeout_ms is set to -1, there is no time-out. This can be used for both fixed and swept mode acquisitions. The WError::ERR_TIMEOUT is a warning code (error code > 0) which can be used to separate behavior from more serious errors.
Parameters:
[in] timeout_ms The number of milliseconds to wait until time-out.
Returns:
WError::ERR_NO_INSTRUMENT if loadInstrument() has not been called. Returns immediately with a WError::ERR_OK if there is no acquisition running. WError::ERR_OK is returned when the measured region has been completed. WError::ERR_TIMEOUT is returned if the function times out before comletion of the point.
See also:
continueAcquisition(), waitForPointReady(), initAcquisition(), startAcquisition(), stopAcquisition()
Definition at line 870 of file wseswrappermain.cpp.
References WError::ERR_NO_INSTRUMENT, WError::ERR_OK, WError::ERR_TIMEOUT, WSESInstrument::GDS_GetStatus, WEvent::handle(), SesNS::NonOperational, and SesNS::Running.
int WSESWrapperMain::zeroSupplies ()
Sets all voltage elements to zero.
Returns:
WError::ERR_NO_INSTRUMENT if loadInstrument() has not been called, WError::ERR_FAIL if the voltages could not be set, otherwise WError::ERR_OK.
Definition at line 495 of file wseswrappermain.cpp.
References WError::ERR_FAIL, WError::ERR_NO_INSTRUMENT, WError::ERR_OK, and WSESInstrument::GDS_ZeroSupplies.
The documentation for this class was generated from the following files:
C:/Development/svn/seswrapper-lib/include/wseswrappermain.h
C:/Development/svn/seswrapper-lib/src/wseswrappermain.cpp